import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Layout from "../components/layout/layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lufga = localFont({
  src: [
    {
      path: "../assets/fonts/lufga/Lufga-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/lufga/Lufga-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/lufga/Lufga-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/lufga/Lufga-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-lufga",
});

const urbanist = localFont({
  src: [
    {
      path: "../assets/fonts/urbanist/Urbanist-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/urbanist/Urbanist-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/urbanist/Urbanist-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/urbanist/Urbanist-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-urbanist",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${lufga.variable} ${urbanist.variable}`}>
          <Layout>
            {children}
          </Layout>
      </body>
    </html>
  );
}
